### ISSUE TITLE
three bugs 

### ISSUE THREAD

**Issue by alexodus** [GoogleCloudPlatform/google-cloud-iot-arduino#66] opened 2018-12-03 16:21 UTC
when compiled into esp-idf structure I obtain this errors:

```
google-cloud-iot-arduino/src/CloudIoTCoreMQTTClient.cpp:94:46: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Werror=format=]
     Serial.printf("Waiting: %ld\n", currDelay);
```

```
google-cloud-iot-arduino/src/CloudIoTCoreMQTTClient.cpp:147:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^

```

in jwt.cpp:
there is this:
```
String CreateJwt(String project_id, long long int time, NN_DIGIT *priv_key) {
  CreateJwt(project_id, time, priv_key, 3600); // one hour default
}
```
the correct is this:
```
String CreateJwt(String project_id, long long int time, NN_DIGIT *priv_key) {
  return CreateJwt(project_id, time, priv_key, 3600); // one hour default
}
```

I made the trivial corrections :P, so excuse me if I don't make a PR

**Comment by gguuss** [comment] 2018-12-04 18:43
Thanks for the heads up, looks like you're seeing compiler warnings?

**Comment by gguuss** [comment] 2018-12-04 18:59
Are you seeing this in the Arduino IDE or are you using another SDK? If you can include a link to what I can do to reproduce the warnings you're seeing, it may be helpful for getting the fix / change in place.

**Comment by alexodus** [comment] 2018-12-04 20:43
I'm using Arduino-esp32 as a component on ESP-IDF

**Comment by alexodus** [comment] 2018-12-04 20:44
1) remove "l" in "%ld" because currDelay is int, not long int
2) missing return
3) missing return

**Comment by alexodus** [comment] 2018-12-04 20:46
about warning....mmmh, I don't remember

**Comment by gguuss** [comment] 2018-12-05 16:41
Got it, I should be able to resolve these soon. Thank you for the report and follow up, it's much appreciated!

**Comment by gguuss** [comment] 2018-12-05 23:53
This should be [resolved in this PR](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/compare/issue-fix?expand=1), for some reason, it broke the examples using the wrapper so I'll have to take a closer look before merging. Will close after merging to master.

**Closed** 2018-12-06 00:56 UTC
