### ISSUE TITLE
Esp32-lwmqtt doesn't connect if xTaskCreate's priority is high

### ISSUE THREAD

**Issue by YIZHUANG** [GoogleCloudPlatform/google-cloud-iot-arduino#73] opened 2019-01-06 22:24 UTC
Basically I added XTaskCreate(sendHumidity, "sendHumidity", 10000, Null, 3,NULL)  in the setup()  from the example, but somehow esp32 is unable to connect to Google cloud over mqtt because of this, but when I change the task priority from 3 to 1, then it connects...
What might be the cause for this? I also tried other examples as well and they all seem to have the same issue as long as I change the task pirotiry to 1 then it works.
I am using PlatformIO.

**Comment by YIZHUANG** [comment] 2019-01-08 19:42
Esp32-lwmqtt.

Is there any other sample that's more stable you would recommend using? All I need is to subscribe to the Google cloud command topic, and send back humidoty via mqtt, so basically two infinite loops....

**Comment by gguuss** [comment] 2019-01-08 20:35
Just pinning a function like:

```Esp32-lwmqtt.ino
    mqttLoop() {
        mqttClient->loop();
    }
```

In order to improve the responsiveness of receiving messages.

**Comment by gguuss** [comment] 2019-01-08 20:46
Also, regarding the issue with the task priority, I can think of a few causes:

* Maybe the task is getting invoked before the JWT is generated
* Maybe the task is taking priority over network access

You could try making sure all other initialization has occurred before starting your task. Can you share your setup code?

**Comment by gguuss** [comment] 2019-03-26 23:13
The following code is working for me:

```c++
void sendHum(void *pvParameter) {
  while(true){
    Serial.println("ahhhhhhhhh");
    vTaskDelay(5000);
    publishTelemetry(getDefaultSensor());
  }
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(LED_BUILTIN, OUTPUT);
  setupCloudIoT();
  xTaskCreate(&sendHum, "sendHum", 10000, NULL, 3, NULL);
}
```

Closing as I cannot reproduce the error, maybe there's something wrong in the humidity device that is causing some other issue?

**Closed by gguuss** 2019-03-26 23:13 UTC
