### ISSUE TITLE
How to handle message published to topic?

### ISSUE THREAD

**Issue by mkroszka** [GoogleCloudPlatform/google-cloud-iot-arduino#198] opened 2020-09-28 13:59 UTC
If I update config or send command to device arduino use messageReceived callback, but if I send message to topic  arduino not responding.

**Comment by amarkevich** [comment] 2020-09-29 10:07
Google IoT support configuration [1] and command [2] topics only. To split commands by custom logic use {subfolder}.

1. https://cloud.google.com/iot/docs/how-tos/config/configuring-devices
2. https://cloud.google.com/iot/docs/how-tos/commands

**Comment by gguuss** [comment] 2020-10-15 21:23
Closing, this is working as intended. Thank you @amarkevich for your help in answering this!

**Closed by gguuss** 2020-10-15 21:23 UTC
